# Site settings
title: Anurup Mondal
description: Programmer, Developer, Entrepreneur.I design and code beautifully simple things, and I love what I do
# baseurl: "/particle" # the subpath of your site, e.g. /blog
 #url: "http://arpan45.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anurup Mondal
user_description: Programmer, Developer, Entrepreneur.I design and code beautifully simple things, and I love what I do
user_title: Software Developer,Designer
email: anurupm1996@gmail.com
github_username:  victordorian1
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

